# -*- coding: utf-8 -*-
"""Avocado_Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipPHILMreptkYVU-OhlGBKY-6PE0qTr8

# PROBLEM STATEMENT

 Data represents weekly 2018 retail scan data for National retail volume (units) and price. Retail scan data comes directly from retailers' cash registers based on actual retail sales of Hass avocados.

  Starting in 2013, the table below reflects an expanded, multi-outlet retail data set. Multi-outlet reporting includes an aggregation of the following channels: grocery, mass, club, drug, dollar and military.

The Average Price (of avocados) in the table reflects a per unit (per avocado) cost, even when multiple units (avocados) are sold in bags.

The Product Lookup codes (PLU's) in the table are only for Hass avocados. Other varieties of avocados (e.g. greenskins) are not included in this table.

 Some relevant columns in the dataset:

 Date The date of the observation

 Average Price the average price of a single avocado

 type - conventional or organic

 year - the year

 Region - the city or region of the observation

 Total Volume - Total number of avocados sold

 4046 - Total number of avocados with PLU 4046 sold

 4225 - Total number of avocados with PLU 4225 sold

 4770 - Total number of avocados with PLU 4770 sold.

# IMPORTING DATA

 You must install fbprophet package as follows: pip install fbprophet

 If you encounter an error, try: conda install -c conda-forge fbprophet

 Prophet is open source software released by Facebook's Core Data Science team.

 Prophet is a procedure for forecasting time series data based on an additive model where non-linear trends are fit with yearly, weekly, and daily seasonality, plus holiday effects.

 Prophet works best with time series that have strong seasonal effects and several seasons of historical data.

 For more information, please check this out: https://research.fb.com/prophet-forecasting-at-scale/https://facebook.github.io/prophet/docs/quick_start.html#python-api

Import Libraries
"""

!pip install prophet
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
import seaborn as sns
from prophet import Prophet

"""Load Dataset"""

df = pd.read_csv('avocado.csv')
print ("Dataset shape", df.shape)
df.head()

df.columns

"""Dataset Information"""

df.info()

"""Statistical Summary"""

df.describe()

"""Check missing value"""

df.isnull().sum()

"""Drop Unnecessary Column"""

df.drop('Unnamed: 0', axis=1, inplace=True)

"""Convert Date Column"""

df['Date'] = pd.to_datetime(df['Date'])

df.info()

"""Sort By Date"""

#Chronological order matters
df = df.sort_values(by='Date')

"""Initial Visualization"""

plt.figure(figsize=(15,6))

plt.plot(df['Date'], df['AveragePrice'])

plt.title('Average Avocado Price Over Time')
plt.xlabel('Date')
plt.ylabel('Average Price')

plt.show()

df['type'].value_counts()

"""Region count"""

df['region'].nunique()

"""Plot Organic vs Conventional Prices"""

plt.figure(figsize=(10,6))

sns.boxplot(x='type', y='AveragePrice', data=df)

plt.title('Organic vs Conventional Avocado Prices')

plt.show()

"""Correlation Analysis

"""

plt.figure(figsize=(12,8))

sns.heatmap(df.corr(numeric_only=True), annot=True)

plt.show()

"""Prepare Data For Prophet"""

prophet_df = df[['Date', 'AveragePrice']]

prophet_df = prophet_df.rename(columns={
    'Date': 'ds',
    'AveragePrice': 'y'
})

prophet_df.head()

plt.figure(figsize=(15,6))

plt.plot(prophet_df['ds'], prophet_df['y'])

plt.title('Avocado Price Time Series')
plt.xlabel('Date')
plt.ylabel('Average Price')

plt.show()

"""Create Prophet Model"""

model = Prophet()

model.fit(prophet_df)

future = model.make_future_dataframe(periods=365)

future.tail()

"""Generate Forecast"""

forecast = model.predict(future)

"""View Forecast Output"""

forecast.head()

"""Plot Forecast"""

figure = model.plot(forecast)

"""Plot Forecast Components"""

figure2 = model.plot_components(forecast)

"""View future forecast only"""

forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()